### PR TITLE
Updated icolbutler-424-1

### PR DESCRIPTION
**Pull request by Spunkle**
Capitalized the first letter of <ms item><class>.

### CODE REVIEW

**Comment by Spunkle** [comment]
I'm testing this for @hapaxlegomenon . Can you you check this is OK? #capitalize

**Comment by hapaxlegomenon** [comment]
@Spunkle @Leonidas-Levine cool cool

**Comment by hapaxlegomenon** [comment]
hi

**Comment by hapaxlegomenon** [comment]
@Spunkle

**Pull request merged**
